### ISSUE TITLE
error uploading photo

### ISSUE THREAD

**Issue by gerkirill** [oleksandrbabenko007/PhotoBox#6]
sometimes error occurs when photo gets uploaded (e.g. it worked fine for 'admin' but failed for 'nata' in my case). Error is the following:

```

PhotoBox/json-storage.js:51
    if (typeof this.data[key] !== 'undefined') {
                        ^

TypeError: Cannot read property 'NaN' of undefined
    at JsonStorage.insert (/home/kirill/www/PhotoBox/json-storage.js:51:25)
    at Busboy.<anonymous> (/home/kirill/www/PhotoBox/server.js:94:20)
    at emitNone (events.js:72:20)
    at Busboy.emit (events.js:166:7)
    at Busboy.emit (/home/kirill/www/PhotoBox/node_modules/connect-busboy/node_modules/busboy/lib/main.js:31:35)
    at /home/kirill/www/PhotoBox/node_modules/connect-busboy/node_modules/busboy/lib/types/multipart.js:52:13
    at nextTickCallbackWith0Args (node.js:420:9)
    at process._tickCallback (node.js:349:13)
```

Please fix.

**Comment by gerkirill** [comment]
merged
